version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sae1013d
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=restroom
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
